"""new fields in user model

Revision ID: 39270db8864c
Revises: b5e79e1fec1d
Create Date: 2022-05-11 10:06:01.039550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39270db8864c'
down_revision = 'b5e79e1fec1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('User', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'last_seen')
    op.drop_column('User', 'about_me')
    # ### end Alembic commands ###
